
export class ResultadosMedEntity{
    constructor(
        public id: number,
        public imc: number,
        public imc_clasificacion: string,
        public gc_kg: number,
        public gc_porcentaje: number,
        public gc_clasificacion: string,
        public gv_kg: number,
        public gv_porcentaje: number,
        public gv_clasificacion: string,
        public mm_kg: number,
        public mm_porcentaje: number,
        public mm_clasificacion: string,
        public imm: number,
        public imm_clasificacion: string,
        public endo: number,
        public meso: number,
        public ecto: number,
        public pha_peso: number,
        public pha_pli_triceps: number,
        public pha_pli_subescapular: number,
        public pha_pli_biceps: number,
        public pha_pli_cresta_iliaca: number,
        public pha_pli_supraespinal: number,
        public pha_pli_abdominal: number,
        public pha_pli_muslo: number,
        public pha_pli_pierna: number,
        public pha_per_brazo: number,
        public pha_per_brazo_flex: number,
        public pha_per_cintura: number,
        public pha_per_cadera: number,
        public pha_per_muslo: number,
        public pha_per_pierna: number,
        public pha_dia_humero: number,
        public pha_dia_biestiloideo: number,
        public pha_dia_femur: number,
        public mediciones_id: number,
        public profesional_id: string,
        public paciente_id: string,
    ){}
}